module.exports = {
    know: [
        "Java",
        "Inheritance",
        "Polymorphism",
        "Threading",
        "JavaScript",
        "ECMAScript 6+",
        "d3.js",
        "p5.js",
        "jQuery",
        "Bootstrap",
        "Ajax",
        "DOM Manipulation",
        "SVG",
        "HTML5 Canvas",
        "Node.js",
        "nodemon",
        "Express",
        "npm",
        "Babel (transpiler)",
        "Vim",
        "Vundle",
        "Tmux",
        "git",
        "GitHub",
        "nmap",
        "netcat",
        "traceroute",
        "SSH",
        "Unix File Systems",
        "fail2ban",
        "iptables",
        "nginx",
        "Flask (Python)",
        "HTML Templating",
        "CSS",
        "CSS media queries",
        "Processing",
        "Arduino",
        "C",
        "Shell Programming",
        "Stack Overflow",
        "gzip compression",
        "tarballs",
        "SSL Certificates",
        "CertBot",
        "cron jobs",
        "Common network ports",
        "Basic TCP",
        "HEIST network attacks",
        "RESTful applications",
        "RESTful applications",
        "The Web API",
        "Web File API",
        "Markdown",
        "TeXmaker",
        "State Diagrams",
        "Basic Computer Architecture",
        "Dvorak Touch Typing (~75 wpm)",
        "Mechanics (Physics)",
        "How to install Linux",
        "The apt(-get) package manager",
        "Homebrew",
        "MongoDB",
        "tor",
        "torsocks (torify)",
        "init.d",
        "Ubuntu",
        "aspell",
        "Hex color system",
        "ColorBrewer scales"
    ].sort(), 
    want : [
        "Haskell",
        "JSON Encryption",
        "HTTP Version 2",
        "Ruby on Rails",
        "Git Cherry-Picking",
        "SQL"
    ].sort(), 
    not : [
        ".NET programming",
        "cmd",
        "PowerShell"
    ].sort()
};

